pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

def cellwatchProperties = new Properties()
file("cellwatch.properties").withInputStream { cellwatchProperties.load(it) }

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                password = 'sk.eyJ1Ijoic2xyb2JlcnRzb242OSIsImEiOiJjbG5scWhqaWoxZGljMnJxaTF1bm1nbTNqIn0.Cqrrxm_03CcRBor8f0WR6Q'
            }
        }
    }
}
rootProject.name = "cellwatch"
include ':app'
